### ISSUE TITLE
Electric field calculation

### ISSUE THREAD

**Issue by olaszsoma** [osrep/Runin#13]
The CPO/IDS databases sometimes don't have parallel electric field data filled, so it has to be calculated from different sources. The calculation has to be implemented to Runin and [Runafluid](https://github.com/osrep/Runafluid) as well, and only has to be used, if the electric field is empty.

**Comment by olaszsoma** [comment]
The problem with the electric field missing in the database might not be relevant anymore, more testing of the ETS is needed with a proper test case, where the electric field is non-zero. In the case of zero electric field, the runaway actors run properly.
It also seemed, that no other code is calculating the electric field, so the evolution of the electric field might not be calculated as time is advanced.

**Comment by gergopokol** [comment]
There is a GForge tracker about this #1544 (https://gforge6.eufus.eu/gf/project/generalsupport/tracker/?action=TrackerItemEdit&tracker_item_id=1544&start=25)

As the tests show on the released ETS version, Runin should not be affected, as it is called after the Convergence loop, so that it is always proceeded by a Transport solver call producing electric field.
